image: ruby:2.7

variables:
  S3_BUCKET_STAGING: "website-maat-digital-staging"
  S3_BUCKET_PRODUCTION: "website-maat-digital"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - rm -Rf public
    - apt-get update -yqqq
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - gem install bundler -v 2.4.22
    - bundle install --path vendor
    - bundle exec middleman build --build-dir=public --clean
  artifacts:
    paths:
      - public

staging:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws s3 sync --sse --delete public s3://$S3_BUCKET_STAGING/ --acl public-read --only-show-errors
  environment:
    name: staging
  only:
    - develop

production:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - export LC_ALL=en_US.UTF-8
    - aws s3 sync --sse --delete public s3://$S3_BUCKET_PRODUCTION/ --acl public-read --only-show-errors
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id E2SROA59G3YQZ5 --paths '/*'
  environment:
    name: production
  only:
    - master
  when: manual
